tracking:
  TRACKING_URI: 'http://localhost:5557'
  EXPERIMENT_NAME: 'sklearn_experiment_8'
  MODEL_NAME: 'test_model_new'
  ARTIFACT_PATH: 'model'
  ARTIFACT_LOCATION: 'file://Users/educauchy/Documents/Dev/DS/Github/typical-project/models/runs'
  MODEL_STAGE: 'None'
  MODEL_VERSION: -1
  random_state: 42
params:
  0: 0
metrics:
  0: 0
data:
  train: './data/external/train.csv'
  test: './data/external/test.csv'
  target: 'target'
  train_size: 0.9
model:
  task_type: 'regression'
  metric: 'neg_mean_squared_error'
  method: 'RandomForestRegressor'
  cv:
    folds: 3
    evals: 3
  random_state: 42
  params:
    max_depth: 1
    n_estimators: 500
  params_hyperopt:
    max_depth: [ 1, 5, 1 ]
#    min_samples_split: [2, 10, 1]
#    min_samples_leaf: [2, 10, 1]
  params_grid:
    impute__n_neighbors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    anomaly__n_neighbors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    cluster__eps: [0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6, 2.8, 3]
    model__n_estimators: [500, 750, 1000, 1250, 1500, 1750, 2000, 2250, 2500, 2750, 3000, 3250, 3500, 3750, 4000]
    model__max_depth: [1, 2, 3, 4, 5]