name: "Data quality"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test columns presence
        run: |
          pytest test_data_quality.py::TestDataQuality::test_columns_presence
      - name: Test columns intervals
        run: |
          pytest test_data_quality.py::TestDataQuality::test_columns_intervals
      - name: Test data drift
        run: |
          pytest test_data_quality.py::TestDataQuality::test_data_drift